remote_theme: mmistakes/minimal-mistakes@4.24.0
# theme: minima
plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji

defaults:
- scope:
    path: ""
  values:
    layout: "single"

minimal_mistakes_skin: "air"

# theme: default
# https://github.com/jekyll/minima
# https://github.com/mmistakes/minimal-mistakes
# https://github.com/pages-themes/cayman
