remote_theme: mmistakes/minimal-mistakes@4.24.0
# theme: minima
plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji

defaults:
- scope:
    path: ""
  values:
    layout: "single"
    comments: true

minimal_mistakes_skin: "default"
title: "Project Augur"
subtitle: "Measuring real-time company performance"

repository: "leetgrouppages/alternativedata"

#comments:
#  provider: "disqus"
#  disqus:
#    shortname: "augur-1"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-5EWW0BPJZ1"
    anonymize_ip: false

# theme: default
# https://github.com/jekyll/minima
# https://github.com/mmistakes/minimal-mistakes
# https://github.com/pages-themes/cayman
