remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache

# theme: minima

# theme: default
# https://github.com/jekyll/minima
# https://github.com/mmistakes/minimal-mistakes
# https://github.com/pages-themes/cayman
