#remote_theme: mmistakes/minimal-mistakes
#plugins:
#- jekyll-remote-theme

theme: minima

# theme: default
# https://github.com/jekyll/minima
# https://github.com/mmistakes/minimal-mistakes
# https://github.com/pages-themes/cayman
